name: GitHub Release Tracker Bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Dependencies
        run: pip install requests matplotlib

      - name: 🚀 Run GitHub Release Checker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          echo "🔍 Checking for GitHub releases..."
          python check_releases.py
          echo "✅ Done."

      - name: 📝 Commit updated JSON and badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add repos.json history.json badges/tracked_count_badge.svg || true
          git commit -m "🔄 Auto update tracked repos and badge" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PUSH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
