name: GitHub Releases Poller

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Poll for new releases and notify channel
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
        run: python poll_github.py

      - name: Commit & Push notification state and badge
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/notified.json badge/tracked-count.json
          git commit -m "Update notified releases and badge [auto]" || echo "Nothing to commit"
          git push
